version: "3"
services:
  influxdb:
    container_name: influxdb:2.7
    restart: unless-stopped
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2

volumes:
  influxdb:
